# Build nsjailcontainer as given in the README on https://github.com/google/nsjail
FROM nsjailcontainer

WORKDIR /app

COPY ./src/index.js .
COPY ./start-nsjail.sh /

RUN chmod +x /start-nsjail.sh

ENTRYPOINT ["/start-nsjail.sh"]
